name: Image Builder
on:
  workflow_dispatch:
  push:
    branches: ["main"] 

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DATABASENAME: ${{ secrets.DB_NAME }}
      DATABASEUSERNAME: ${{ secrets.DB_USERNAME }}
      DATABASEPASSWORD: ${{ secrets.DB_PASSWORD }}
      DATABASEURL: ${{ secrets.DB_URL }}
      ENVRUN: ${{ secrets.ENV_RUN }}

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 20
        
    - name: Start sql services
      run: sudo systemctl start mysql.service 
    - name: Install dependencies    
      run: npm ci
    - name: Running tests
      run: npm test

    - name: Zip webapp 
      run: |
        zip -r webapp.zip ./
        ls 

    - name: Install and Configure gcloud CLI
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_KEY }}'
        export_default_credentials: true

    - name: Setup packer
      uses: hashicorp/setup-packer@main
      id: setup
      with:
        version: "1.10.1"

    - name: Packer init
      run: packer init .

    - name: Packer Format
      run: packer fmt -check .

    - name: Packer Validate
      run: packer validate gcp.pkr.hcl

    - name: Packer Builder
      run: packer build gcp.pkr.hcl
    
    - name: Get Image id
      run: |
        IMAGE_ID=$(packer output -json my_image_id | jq -r '.my_image_id.value')
        echo "IMAGE_ID=$IMAGE_ID" >> $GITHUB_ENV
        echo "Built GCP image ID is $IMAGE_ID"

    - name: Generate Version
      run: |
        VERSION=$(date +%Y%m%d%H%M%S)
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        ehco "Version is $VERSION"

    - name: New Instance Template
      run: |
        gcloud compute instance-templates create "instance-template-${{ env.VERSION }}" \
        --image="${{ env.IMAGE_ID }}" \
        --image-family="custom-family" \
        --machine-type="e2-medium" \
        --region="us-east1" \
        --tags="webapp" \
        --network="vpc-network1" \
        --subnet="subnet1" \
        --network-tier="PREMIUM" \
        --boot-disk-size=100GB \
        --boot-disk-type="pd-balanced" \
        --disk auto-delete=yes \
        --lifecycle "create-before-destroy" \
        --maintenance-policy="MIGRATE" \
        --service-account="webapp-service-account@csye6225-414123.iam.gserviceaccount.com" \
        --scopes=logging-write,monitoring-write,cloud-platform,pubsub \
        --metadata-from-file startup-script=<(cat <<EOF
        sudo touch /opt/app/.env
        echo "DATABASEUSERNAME=webapp" >> /opt/app/.env
        echo "DATABASEURL=10.150.0.2" >> /opt/app/.env
        echo "DATABASEPASSWORD=UtLGHhb9Z5CSDiu5" >> /opt/app/.env
        echo "DATABASENAME=webapp" >> /opt/app/.env
        echo "ENVRUN=PRODUCTION" >> /opt/app/.env
        EOF
        )
