name: Image Builder
on:
  workflow_dispatch:
  push:
    branches: ["main"] 

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DATABASENAME: ${{ secrets.DB_NAME }}
      DATABASEUSERNAME: ${{ secrets.DB_USERNAME }}
      DATABASEPASSWORD: ${{ secrets.DB_PASSWORD }}
      DATABASEURL: ${{ secrets.DB_URL }}
      ENVRUN: ${{ secrets.ENV_RUN }}

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 20
        
    - name: Start sql services
      run: sudo systemctl start mysql.service 
    - name: Install dependencies    
      run: npm ci
    - name: Running tests
      run: npm test

    - name: Zip webapp 
      run: |
        zip -r webapp.zip ./
        ls 

    - name: Install and Configure gcloud CLI
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_KEY }}'
        export_default_credentials: true

    - name: Setup packer
      uses: hashicorp/setup-packer@main
      id: setup
      with:
        version: "1.10.1"

    - name: Packer init
      run: packer init .

    - name: Packer Format
      run: packer fmt -check .

    - name: Packer Validate
      run: packer validate gcp.pkr.hcl

    

    - name: Generate version number
      run: echo "VERSION=$(date +%s)" >> $GITHUB_ENV


    - name: New Instance Template
      run: |
        gcloud compute instance-templates create "instance-template-${{ env.VERSION }}" \
        --project="${{ secrets.PROJECTID }}" \
        --image="custom-machine-image-2024-04-10-19-08-49" \
        --machine-type="${{ secrets.MACHINE_TYPE }}" \
        --region="${{ secrets.REGION }}" \
        --tags="${{ secrets.TAGS }}" \
        --network="${{ secrets.NETWORK }}" \
        --subnet=${{ secrets.SUBNET }}" \
        --network-tier="${{ secrets.NETWORKTIER }}" \
        --boot-disk-size="${{ secrets.DISKSIZE }}" \
        --boot-disk-type="${{ secrets.DISKTYPE }}" \
        --instance-template-region="${{ secrets.REGION }}" \
        --boot-disk-kms-key="projects/${{ secrets.PROJECTID }}/locations/us-east1/keyRings/${{ secrets.KMSRING }}/cryptoKeys/vm-key" \
        --boot-disk-device-name="webapp-instance" \
        --maintenance-policy="MIGRATE" \
        --service-account="webapp-service-account@${{ secrets.PROJECTID }}.iam.gserviceaccount.com" \
        --scopes="${{ secrets.SCOPES }}" \
        --metadata=startup-script='#!/bin/bash
        cat > /opt/app/.env << End
        DATABASEUSERNAME=webapp
        DATABASEURL=192.168.0.2
        DATABASEPASSWORD=CutHZF7BaedoOMEW
        DATABASENAME=webapp
        ENVRUN=PRODUCTION
        End'

    - name: Start Rolling Update
      run: |
        gcloud compute instance-groups managed rolling-action start-update ${{ secrets.MIGNAME }} \
        --version='template=projects/${{ secrets.PROJECTID }}/regions/${{ secrets.REGION }}/instanceTemplates/instance-template-${{ env.VERSION }}' \
        --region="${{ secrets.REGION }}" \
        --project="${{ secrets.PROJECTID }}" \

    - name: Wait for refresh to complete 
      run: |
        gcloud compute instance-groups managed wait-until ${{ secrets.MIGNAME }} \
        --version-target-reached \
        --region ${{ secrets.REGION }}