# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Test.js CI

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      DATABASENAME: dbname
      DATABASEUSERNAME: uname
      DATABASEPASSWORD: passwordz

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: dbname
          MYSQL_USER: uname
          MYSQL_PASSWORD : passwordz
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependencies    
      run: npm ci
    - name: Running tests
      run: |
          export DATABASENAME=$DATABASENAME
          export DATABASEUSERNAME=$DATABASEUSERNAME
          export DATABASEPASSWORD=$DATABASEPASSWORD
          npm test
